#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
        list)
                echo '{ "upgrade_test" : {}, "upgrade_start" : {} }'
        ;;
        call)
                case "$2" in
                        upgrade_test)
                        		invalid=`cat /tmp/firmware.bin`
                        		if [ $invalid = "Invalid" ]; then
                        			cat /tmp/rpc_sys_fail.data 2>/dev/null
                        		else
                        			cat /tmp/rpc_sys.data 2>/dev/null
                        		fi
                        ;;
                        upgrade_start)
                                cat /tmp/rpc_sys.data 2>/dev/null
                                sleep 7
                                supervisorctl stop icwmpd >> ./funl-test-debug.log
                        ;;
                esac
        ;;
esac
