[program:ubusd]
priority=1
command=/bin/bash -c "/usr/sbin/ubusd"

[program:rpcd]
priority=2
command=/bin/bash -c "/usr/sbin/rpcd"

[program:download]
priority=3
command=/bin/bash -c "cd /tmp/firmware/ && python3 -m http.server 80"

[program:bbfdmd]
priority=4
command=/bin/bash -c "/usr/sbin/bbfdmd"
